// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2IGCD-0Yh_JLHC9ujoR3buC7NGVRBJJU',
    appId: '1:432820630610:web:0414f667aeeb7126f9db8b',
    messagingSenderId: '432820630610',
    projectId: 'currensee-ce2a8',
    authDomain: 'currensee-ce2a8.firebaseapp.com',
    storageBucket: 'currensee-ce2a8.firebasestorage.app',
    measurementId: 'G-1HR2Y7NV4W',
    databaseURL: 'https://currensee-ce2a8-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4rtM0v2oU4tUxrzUC8LEv84elycwPmf8',
    appId: '1:432820630610:android:584e232952ca17a7f9db8b',
    messagingSenderId: '432820630610',
    projectId: 'currensee-ce2a8',
    storageBucket: 'currensee-ce2a8.firebasestorage.app',
    databaseURL: 'https://currensee-ce2a8-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTaM45DWJ5xQTy8ivJM7UskEK8CL2xMfo',
    appId: '1:432820630610:ios:17f8290565ba7417f9db8b',
    messagingSenderId: '432820630610',
    projectId: 'currensee-ce2a8',
    storageBucket: 'currensee-ce2a8.firebasestorage.app',
    iosBundleId: 'com.example.currensee',
    databaseURL: 'https://currensee-ce2a8-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTaM45DWJ5xQTy8ivJM7UskEK8CL2xMfo',
    appId: '1:432820630610:ios:17f8290565ba7417f9db8b',
    messagingSenderId: '432820630610',
    projectId: 'currensee-ce2a8',
    storageBucket: 'currensee-ce2a8.firebasestorage.app',
    iosBundleId: 'com.example.currensee',
    databaseURL: 'https://currensee-ce2a8-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2IGCD-0Yh_JLHC9ujoR3buC7NGVRBJJU',
    appId: '1:432820630610:web:6577303ece921117f9db8b',
    messagingSenderId: '432820630610',
    projectId: 'currensee-ce2a8',
    authDomain: 'currensee-ce2a8.firebaseapp.com',
    storageBucket: 'currensee-ce2a8.firebasestorage.app',
    measurementId: 'G-F2HLMK4MR0',
    databaseURL: 'https://currensee-ce2a8-default-rtdb.firebaseio.com/',
  );
}
